
[general]
import = [] # Add paths to external theme files here if desired

[window]
opacity = 0.95

blur = true

[font]
size = 10.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

