[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }


[[language]]
name = "bash"
formatter = { command = "shfmt" }

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "python"
roots = [".git"]
language-servers = ["ruffls"]

[[language]]
name = "tsx"
roots = [".git"]
language-servers = ["oxlint", "vtsls", "emmet-lsp", "tailwindcss-ls"]

[[language]]
name = "javascript"
roots = [".git"]
language-servers = ["oxlint", "vtsls", "emmet-lsp", "tailwindcss-ls"]

[[language]]
name = "typescript"
roots = [".git"]
language-servers = ["oxlint", "vtsls", "emmet-lsp", "tailwindcss-ls"]

[[language]]
name = "html"
roots = [".git"]
language-servers = [
  "vscode-html-language-server",
  "emmet-lsp",
  "tailwindcss-ls",
]
#LSP
[language-server.emmet-lsp]
command = "emmet-ls"
args = ["--stdio"]

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.oxlint]
command = "oxlint"
args = ["--lsp"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
[language-server.ruffls]
command = "ruff"
args = ["server"]
